### PR TITLE
Make MobilityRansack handle associations correctly

### LINKED ISSUE #18: Searching for objects in belongs_to associations
Isn't that possible or am I missing something? For instance:

```
class Athlete < ApplicationRecord
	belongs_to :playing_position
end

class PlayingPosition < ApplicationRecord
	extend Mobility
	
	translates :name
end
```

pry(main)> Athlete.ransack(playing_position_name_cont: 'pont').result.size
   (0.7ms)  SELECT COUNT(*) FROM `athletes` LEFT OUTER JOIN `playing_positions` ON `playing_positions`.`id` = `athletes`.`playing_position_id` WHERE `PlayingPosition_name_pt_br_string_translations`.`value` LIKE '%pont%'
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'PlayingPosition_name_pt_br_string_translations.value' in 'where clause'
from /Users/fabiano/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
Caused by Mysql2::Error: Unknown column 'PlayingPosition_name_pt_br_string_translations.value' in 'where clause'
from /Users/fabiano/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'

### PR DESCRIPTION
**Pull request by shioyama**
Fixes #18

### CODE REVIEW

**Comment by shioyama** [comment]
cc @fabianof @jalkoby

File: lib/mobility/ransack.rb [hunk 1]
```diff
@@ -1,6 +1,56 @@
...
+
+      def visit_collection(objects)
+        objects.map(&method(:visit)).sum.uniq
+      end
+      alias :visit_Array :visit_collection
+      alias :visit_Arel_Nodes_Equality :visit_Arel_Nodes_Binary
+      alias :visit_Arel_Nodes_Or :visit_Arel_Nodes_Binary
+
+      def visit_Mobility_Plugins_Arel_Attribute(object)
+        [[object.backend_class, object.locale]]
```
Comment (shioyama) [inline lib/mobility/ransack.rb:22]: This is relying on the undocumented fact that backends which require applying additional scope (KeyValue and Table) define their nodes as objects of class `Mobility::Plugins::Arel::Attribute`. If this were not the case then this would not work.

I think Mobility could have a better way to just say:

```ruby
Mobility.apply_scope do
  # some stuff with backend nodes
end
```

and it would _just work_. Then we could just use that here. But that would require a documented standard for how to define backend nodes which require applied scopes (i.e. backends that require joins) which we don't currently have.

Anyway this should work for now. Maybe we can add something like this to Mobility 1.2 :thinking:

File: lib/mobility/ransack.rb [hunk 2]
```diff
@@ -1,6 +1,56 @@
...
+          backend_class.apply_scope(i18n_rel, predicate, locale)
+        end
+      end
+
+      def visitor
+        @visitor ||= Visitor.new
+      end
+    end
+
+    ::Ransack::Search.prepend Search
```
Comment (shioyama) [inline lib/mobility/ransack.rb:54]: I don't really like globally patching like this but I don't see how else to support associations from models that don't use Mobility.
